Web_Lab3/Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_Lab3.Models
{
    public class Quiz
    {
        public int Number1 { get; set; }
        public int Number2 { get; set; }
        public string Operation { get; set; }
        public int RightAnswer { get; set; }
        public int UserAnswer { get; set; }
        public string QueryStr { get; set; }
    }
}

Web_Lab3/Controllers/MockupsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_Lab3.Models;
using Web_Lab3.Services;

namespace Web_Lab3.Controllers
{
    public class MockupsController : Controller
    {
        private QuizService _quizService;
        public MockupsController()
        {
            _quizService = QuizService.Instance;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Quiz()
        {
            _quizService.Reset();
            var quiz = _quizService.GetNewQuiz();
            return View(quiz);
        }

        [HttpPost]
        public IActionResult Quiz(string action)
        {
            if (!ModelState.IsValid)
                return BadRequest("Not validated");

            var quiz = _quizService.GetLastQuiz();

            quiz.UserAnswer = !String.IsNullOrEmpty(Request.Form["Answer"]) 
                ? Int32.Parse(Request.Form["Answer"]) 
                : 0;
            quiz.QueryStr += quiz.UserAnswer.ToString();
            _quizService.AddQuizToList(quiz);

            if (action == "Next")
                return View(_quizService.GetNewQuiz());

            return RedirectToAction("QuizResult");

        }

        public IActionResult QuizResult()
        {
            var list = _quizService.GetListQuizzes();
            if (list is not null)
            {
                ViewBag.Result = list.Select(s => s.QueryStr);
                ViewData["All"] = "" + list.Count;
                ViewData["Right"] = "" + list.Count(s => s.RightAnswer == s.UserAnswer);
            }
            return View();
        }
    }
}

Web_Lab3/Views/Mockups/Index.cshtml
<h1>Mockups</h1>
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Mockups" asp-action="Quiz">Quiz</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Mockups" asp-action="QuizResult">QuizResult</a>
    </li>
</ul>

Web_Lab3/Views/Mockups/Quiz.cshtml
@model Web_Lab3.Models.Quiz
<h2>Quiz</h2>
<b>@Model.Number1  @Model.Operation @Model.Number2 =</b>
<br />
<form asp-controller="Mockups">
    <input name="Answer" class="mb-3 mr-3" /><br />
    <div class="mb-3">
        <input type="submit" value="Next" name="action" class="btn btn-outline-secondary btn-sm" />
        <input type="submit" value="Finish" name="action" class="btn btn-primary btn-sm" />
    </div>
</form>

Web_Lab3/Views/Mockups/QuizResult.cshtml
<h2>Quiz results</h2>
@if (ViewBag.Result != null)
{
    <h4>Right answers @ViewData["Right"] out @ViewData["All"]</h4>
    <ol>
        @foreach (var p in (ViewBag.Result))
        {
            <li>@p</li>
        }
    </ol>
}
else
{
    <h4>Not results</h4>
}

Web_Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend 3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Mockups" asp-action="Index">Backend 3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Backend 3
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>